In [12]:
import pandas as pd
from datetime import date, datetime
from bs4 import BeautifulSoup
import requests
import time
from tqdm import tqdm
from pathlib import Path

## UFC Events

### 1. Events till UFC-308

In [13]:
script_dir=Path.cwd()
file_path=script_dir.parent/"historical_data"/"ufc_events.csv"

In [14]:
df = pd.read_csv(file_path)
df.head()

,event_id,event_name,event_date,url_link
0,1,UFC Fight Night: Magny vs. Prates,2024-11-09,http://www.ufcstats.com/event-details/585f9ffd...
1,2,UFC Fight Night: Moreno vs. Albazi,2024-11-02,http://www.ufcstats.com/event-details/3ab0df1d...
2,3,UFC 308: Topuria vs. Holloway,2024-10-26,http://www.ufcstats.com/event-details/221b2a30...
3,4,UFC Fight Night: Hernandez vs. Pereira,2024-10-19,http://www.ufcstats.com/event-details/6a0047ac...
4,5,UFC Fight Night: Royval vs. Taira,2024-10-12,http://www.ufcstats.com/event-details/5bdcbd8d...

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 711 entries, 0 to 710
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   event_id    711 non-null    int64
 1   event_name  711 non-null    str
 2   event_date  711 non-null    str
 3   url_link    711 non-null    str
dtypes: int64(1), str(3)
memory usage: 22.3 KB

In [16]:
urls_1 = list(df['url_link'])
len(urls_1)

711

### 2. Events from UFC-309

In [17]:
urls= [
    'http://www.ufcstats.com/event-details/daff32bc96d1eabf',
    'http://www.ufcstats.com/event-details/e955046551f8c7dd',
    'http://www.ufcstats.com/event-details/ad23903ef3af7406',
    'http://www.ufcstats.com/event-details/72c9c2eadfc3277e',
    'http://www.ufcstats.com/event-details/81ddc98fceb30086',
    'http://www.ufcstats.com/event-details/39f68882def7a507',
    'http://www.ufcstats.com/event-details/80dbeb1dd5b53e64',
    'http://www.ufcstats.com/event-details/e6015889f50075d2',
    'http://www.ufcstats.com/event-details/ce7871949b0ed2bf',
    'http://www.ufcstats.com/event-details/c50ea21fe9ef478d',
    'http://www.ufcstats.com/event-details/9766ed20b68c7c33',
    'http://www.ufcstats.com/event-details/ca936c67687789e9',
    'http://www.ufcstats.com/event-details/39f62b833e4cf126',
    'http://www.ufcstats.com/event-details/cc2ad11b1f9d818b',
    'http://www.ufcstats.com/event-details/0f7210aa8d61af8d',
    'http://www.ufcstats.com/event-details/86b30a86664cb6e4',
    'http://www.ufcstats.com/event-details/22f4b6cb6b1bd7fd',
    'http://www.ufcstats.com/event-details/b2e3aca4cd363477',
    'http://www.ufcstats.com/event-details/de20ffb3fc2e7629',
    'http://www.ufcstats.com/event-details/118463dd8db16e7f',
    'http://www.ufcstats.com/event-details/8ad022dd81224f61',
    'http://www.ufcstats.com/event-details/2a898bf9fb7710b3',
    'http://www.ufcstats.com/event-details/18c49685296c60e6',
    'http://www.ufcstats.com/event-details/de277a4abcfeea46',
    'http://www.ufcstats.com/event-details/400c7b43c86d27d3',
    'http://www.ufcstats.com/event-details/66766984842c13dc',
    'http://www.ufcstats.com/event-details/7b03d9df5910917d',
    'http://www.ufcstats.com/event-details/b8e2f10efb6eca85',
    'http://www.ufcstats.com/event-details/28d8638ea0a71908',
    'http://www.ufcstats.com/event-details/f2c934689243fe4e',
    'http://www.ufcstats.com/event-details/6cd3dfc54f01287f',
    'http://www.ufcstats.com/event-details/421ccfc6ddb17958',
    'http://www.ufcstats.com/event-details/8fbcd82bf7f352bf',
    'http://www.ufcstats.com/event-details/754968e325d6f60d',
    'http://www.ufcstats.com/event-details/6e380a4d73ab4f0e',
    'http://www.ufcstats.com/event-details/5efaaf313b652dd7',
    'http://www.ufcstats.com/event-details/ed220e87bef0cc64',
    'http://www.ufcstats.com/event-details/8944a0f9b2f0ce6d',
    'http://www.ufcstats.com/event-details/9336e86cfd4ceaa1',
    'http://www.ufcstats.com/event-details/38e5d9dcb0fddc42',
    'http://www.ufcstats.com/event-details/7956f026e2672c47',
    'http://www.ufcstats.com/event-details/0e2c2daf11b5d8f2',
    'http://www.ufcstats.com/event-details/6436029b50a9c255',
    'http://www.ufcstats.com/event-details/8db1b36dde268ef6',
    'http://www.ufcstats.com/event-details/92c96df8bdab5fea',
    'http://www.ufcstats.com/event-details/bd92cf5da5413d2a',
    'http://www.ufcstats.com/event-details/bc0f994de0521926',
    'http://www.ufcstats.com/event-details/00e11b5c8b7bfeeb',
    'http://www.ufcstats.com/event-details/30ad2050273d016a',
    'http://www.ufcstats.com/event-details/c337c3c85b1871e0',
    'http://www.ufcstats.com/event-details/79ab17db3b40831a',
    'http://www.ufcstats.com/event-details/0cfbbfa0ba6d9855',
    'http://www.ufcstats.com/event-details/15ec018d144710db',
    'http://www.ufcstats.com/event-details/babc6b5745335f18',
]

In [18]:
len(urls)

54

### 3. Total urls

In [19]:
urls.extend(urls_1)
len(urls)

765

### Batch extract time

In [20]:
batch_extract_time = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

### Extracting data from urls

#### via threadpooling

In [21]:
import concurrent.futures

def scrap_event_data(url):
    events_fight_data = []

    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}

    try:
        response = requests.get(url, headers=headers, timeout=10)
        # response = session.get(url, timeout=5)
        soup = BeautifulSoup(response.text, 'html.parser')

        event_name = soup.find('h2', class_='b-content__title').text.strip()

        events_venue = soup.find_all('li', class_='b-list__box-list-item')
        event_date, event_location = [li.text.strip().split('\n')[-1].strip() for li in events_venue]

        rows = soup.find_all('tr', class_='b-fight-details__table-row')

        for row in rows[1:]:
            cols = row.find_all('td', class_='b-fight-details__table-col')

            
            fighter_1, fighter_2 = [p.text.strip() for p in cols[1].find_all('p')]
            fighter_1_url, fighter_2_url = [a['href'] for a in cols[1].find_all('a')]

            # col[0] --> fight details
            fight_details = [p for p in cols[0].find_all('p')]
            req_details = [{'fight_url':detail.find('a')['href'], 'status_flag':detail.find('i', class_='b-flag__text').text.strip()} for detail in fight_details]
            status_flag = req_details[0]['status_flag']
            fight_url = req_details[0]['fight_url'] # for fact_fights id
            
            match_outcome = status_flag

            if match_outcome == 'win':
                winer_name = fighter_1
                winner_url = fighter_1_url
            else:
                winer_name = status_flag
                winner_url = None


            # result = cols[1].find_all('p')[0].text.strip()
            # result_url = fighter_1_url

            # knockdown
            kd_1, kd_2 = [p.text.strip() for p in cols[2].find_all('p')]
            kd = f"{kd_1}-{kd_2}"

            # strikes
            str_1, str_2 = [p.text.strip() for p in cols[3].find_all('p')]
            strikes = f"{str_1}-{str_2}"

            # takedown
            td_1, td_2 = [p.text.strip() for p in cols[4].find_all('p')]
            td = f"{td_1}-{td_2}"

            # submission
            sub_1, sub_2 = [p.text.strip() for p in cols[5].find_all('p')]
            sub = f"{sub_1}-{sub_2}"

            weight_class = cols[6].find('p').text.strip()
            method_list = [method.text.strip() for method in cols[7].find_all('p')]
            method = "-".join(method_list)

            round_num = cols[8].find('p').text.strip()
            fight_time = cols[9].find('p').text.strip()

            event_data = {
                'event_name':event_name,
                'event_date':event_date,
                'event_location':event_location,
                'event_url':url,
                'fight_url':fight_url,
                'match_outcome':match_outcome,
                'fighter_1':fighter_1,
                'fighter_1_url':fighter_1_url,
                'fighter_2':fighter_2,
                'fighter_2_url':fighter_2_url,
                'winner_name':winer_name,
                'winner_url':winner_url,
                'kd':kd,
                'strikes':strikes,
                'td':td,
                'sub':sub,
                'weight_class':weight_class,
                'method':method,
                'round_num':round_num,
                'fight_time':fight_time,
                'extracted_at':batch_extract_time
            }
            
            events_fight_data.append(event_data)

    except Exception as e:
        print(f"\nFailed on {url}: {e}")
        pass

    return events_fight_data

In [22]:
workers = 8

all_scraped_event_data = []

with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as executor:
    results = list(
        tqdm(
            executor.map(scrap_event_data, urls),
            total=len(urls),
            desc="Scarping UFC events"
        )
    )

for event_result in results:
    all_scraped_event_data.extend(event_result)

Scarping UFC events: 100%|██████████| 765/765 [02:54<00:00,  4.39it/s]

In [23]:
events_df = pd.DataFrame(all_scraped_event_data)
print(f"Scraping complete..Total fights extracted: {len(events_df)}")

Scraping complete..Total fights extracted: 8586

In [24]:
events_df.head(5)

,event_name,event_date,event_location,event_url,fight_url,match_outcome,fighter_1,fighter_1_url,fighter_2,fighter_2_url,...,winner_url,kd,strikes,td,sub,weight_class,method,round_num,fight_time,extracted_at
0,UFC 309: Jones vs. Miocic,"November 16, 2024","New York City, New York, USA",http://www.ufcstats.com/event-details/daff32bc...,http://www.ufcstats.com/fight-details/b35e47f2...,win,Jon Jones,http://www.ufcstats.com/fighter-details/07f72a...,Stipe Miocic,http://www.ufcstats.com/fighter-details/d28dee...,...,http://www.ufcstats.com/fighter-details/07f72a...,1-0,96-37,1-0,0-0,Heavyweight,KO/TKO-Spinning Back Kick,3,4:29,2026-04-05 09:04:40
1,UFC 309: Jones vs. Miocic,"November 16, 2024","New York City, New York, USA",http://www.ufcstats.com/event-details/daff32bc...,http://www.ufcstats.com/fight-details/4f418900...,win,Charles Oliveira,http://www.ufcstats.com/fighter-details/07225b...,Michael Chandler,http://www.ufcstats.com/fighter-details/4b93a8...,...,http://www.ufcstats.com/fighter-details/07225b...,0-0,88-84,5-0,2-0,Lightweight,U-DEC-,5,5:00,2026-04-05 09:04:40
2,UFC 309: Jones vs. Miocic,"November 16, 2024","New York City, New York, USA",http://www.ufcstats.com/event-details/daff32bc...,http://www.ufcstats.com/fight-details/cfd3e62c...,win,Bo Nickal,http://www.ufcstats.com/fighter-details/35673b...,Paul Craig,http://www.ufcstats.com/fighter-details/eabf20...,...,http://www.ufcstats.com/fighter-details/35673b...,0-0,54-47,0-0,0-0,Middleweight,U-DEC-,3,5:00,2026-04-05 09:04:40
3,UFC 309: Jones vs. Miocic,"November 16, 2024","New York City, New York, USA",http://www.ufcstats.com/event-details/daff32bc...,http://www.ufcstats.com/fight-details/8545a249...,win,Viviane Araujo,http://www.ufcstats.com/fighter-details/36541f...,Karine Silva,http://www.ufcstats.com/fighter-details/9d62c2...,...,http://www.ufcstats.com/fighter-details/36541f...,0-0,48-58,3-1,1-1,Women's Flyweight,U-DEC-,3,5:00,2026-04-05 09:04:40
4,UFC 309: Jones vs. Miocic,"November 16, 2024","New York City, New York, USA",http://www.ufcstats.com/event-details/daff32bc...,http://www.ufcstats.com/fight-details/55eebc2e...,win,Mauricio Ruffy,http://www.ufcstats.com/fighter-details/9c393e...,James Llontop,http://www.ufcstats.com/fighter-details/93b2b7...,...,http://www.ufcstats.com/fighter-details/9c393e...,1-0,67-90,0-0,0-0,Catch Weight,U-DEC-,3,5:00,2026-04-05 09:04:40

In [25]:
events_df.info()

<class 'pandas.DataFrame'>
RangeIndex: 8586 entries, 0 to 8585
Data columns (total 21 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   event_name      8586 non-null   str
 1   event_date      8586 non-null   str
 2   event_location  8586 non-null   str
 3   event_url       8586 non-null   str
 4   fight_url       8586 non-null   str
 5   match_outcome   8586 non-null   str
 6   fighter_1       8586 non-null   str
 7   fighter_1_url   8586 non-null   str
 8   fighter_2       8586 non-null   str
 9   fighter_2_url   8586 non-null   str
 10  winner_name     8586 non-null   str
 11  winner_url      8434 non-null   str
 12  kd              8586 non-null   str
 13  strikes         8586 non-null   str
 14  td              8586 non-null   str
 15  sub             8586 non-null   str
 16  weight_class    8586 non-null   str
 17  method          8586 non-null   str
 18  round_num       8586 non-null   str
 19  fight_time      8586 non-null   str
 20  extracted_at    8586 non-null   str
dtypes: str(21)
memory usage: 1.4 MB

In [26]:
events_df['event_date'] = pd.to_datetime(events_df['event_date'])
events_df = events_df.sort_values(by='event_date', ascending=False).reset_index(drop=True)

In [27]:
events_df.head(5)

,event_name,event_date,event_location,event_url,fight_url,match_outcome,fighter_1,fighter_1_url,fighter_2,fighter_2_url,...,winner_url,kd,strikes,td,sub,weight_class,method,round_num,fight_time,extracted_at
0,UFC Fight Night: Emmett vs. Vallejos,2026-03-14,"Las Vegas, Nevada, USA",http://www.ufcstats.com/event-details/babc6b57...,http://www.ufcstats.com/fight-details/8bee5192...,win,Jose Delgado,http://www.ufcstats.com/fighter-details/7d6cef...,Andre Fili,http://www.ufcstats.com/fighter-details/8fd808...,...,http://www.ufcstats.com/fighter-details/7d6cef...,0-0,94-62,1-4,0-0,Featherweight,S-DEC-,3,5:00,2026-04-05 09:04:40
1,UFC Fight Night: Emmett vs. Vallejos,2026-03-14,"Las Vegas, Nevada, USA",http://www.ufcstats.com/event-details/babc6b57...,http://www.ufcstats.com/fight-details/f44b4e99...,win,Elijah Smith,http://www.ufcstats.com/fighter-details/7478b7...,SuYoung You,http://www.ufcstats.com/fighter-details/a474aa...,...,http://www.ufcstats.com/fighter-details/7478b7...,1-0,16-3,0-4,1-0,Bantamweight,SUB-Rear Naked Choke,2,1:04,2026-04-05 09:04:40
2,UFC Fight Night: Emmett vs. Vallejos,2026-03-14,"Las Vegas, Nevada, USA",http://www.ufcstats.com/event-details/babc6b57...,http://www.ufcstats.com/fight-details/e0acd0cf...,win,Marwan Rahiki,http://www.ufcstats.com/fighter-details/6eedb7...,Harry Hardwick,http://www.ufcstats.com/fighter-details/2dbc60...,...,http://www.ufcstats.com/fighter-details/6eedb7...,0-0,90-65,0-0,0-0,Featherweight,KO/TKO-,2,5:00,2026-04-05 09:04:40
3,UFC Fight Night: Emmett vs. Vallejos,2026-03-14,"Las Vegas, Nevada, USA",http://www.ufcstats.com/event-details/babc6b57...,http://www.ufcstats.com/fight-details/db7694f4...,win,Ion Cutelaba,http://www.ufcstats.com/fighter-details/cd1372...,Oumar Sy,http://www.ufcstats.com/fighter-details/46e201...,...,http://www.ufcstats.com/fighter-details/cd1372...,0-0,14-5,1-0,1-0,Light Heavyweight,SUB-Guillotine Choke,1,4:24,2026-04-05 09:04:40
4,UFC Fight Night: Emmett vs. Vallejos,2026-03-14,"Las Vegas, Nevada, USA",http://www.ufcstats.com/event-details/babc6b57...,http://www.ufcstats.com/fight-details/f594fc5c...,win,Kevin Vallejos,http://www.ufcstats.com/fighter-details/239d8e...,Josh Emmett,http://www.ufcstats.com/fighter-details/fba03c...,...,http://www.ufcstats.com/fighter-details/239d8e...,2-0,36-3,0-0,0-0,Featherweight,KO/TKO-Punches,1,3:33,2026-04-05 09:04:40

In [28]:
output_file_path=script_dir.parent/"data"/"historical_ufc_events_scraped.csv"

events_df.to_csv(output_file_path, index=False)

In [29]:
events_df['match_outcome'].unique()

<StringArray>
['win', 'nc', 'draw']
Length: 3, dtype: str

## All UFC Fighters

### Scrap fighter data via threadpool

In [29]:
import concurrent.futures

def scrap_fighter_data(fighter_url):

    all_fighters_data = []

    headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}

    try:
        response = requests.get(fighter_url, headers=headers, timeout=10)
        soup = BeautifulSoup(response.text, 'html.parser')

        rows = soup.find_all(class_='b-statistics__table-row')

        for row in rows[2:]:
            cols = row.find_all(class_='b-statistics__table-col')

            first = cols[0].text.strip()
            last = cols[1].text.strip()
            nickname = cols[2].text.strip()
            a_tag = cols[0].find('a')
            fighter_url = a_tag.get('href') if a_tag else "No URL"
            ht = cols[3].text.strip()
            wt = cols[4].text.strip()
            reach = cols[5].text.strip()
            stance = cols[6].text.strip()
            w = cols[7].text.strip()
            l = cols[8].text.strip()
            d = cols[9].text.strip()
            belt = cols[10].text.strip()
            belt_img = cols[10].find('img')
            belt = "Yes" if belt_img else "No"

            fighter_data = {
                'first_name':first,
                'last_name':last,
                'nickname':nickname,
                'fighter_url':fighter_url,
                'height':ht,
                'weight':wt,
                'reach':reach,
                'stance':stance,
                'win':w,
                'lose':l,
                'draw':d,
                'belt':belt,
                'extracted_at':batch_extract_time
            }

            all_fighters_data.append(fighter_data)

    except Exception as e:
        print(f"\nFailed on {fighter_url}: {e}")
        pass

    return all_fighters_data

In [30]:
from string import ascii_lowercase

fighter_urls = [f"http://www.ufcstats.com/statistics/fighters?char={letter}&page=all" for letter in ascii_lowercase]

# len(fighter_urls)

workers = 8

all_scraped_fighter_data = []

with concurrent.futures.ThreadPoolExecutor(max_workers=workers) as executor:
    results = list(
        tqdm(
            executor.map(scrap_fighter_data, fighter_urls),
            total=len(fighter_urls),
            desc="Scarping UFC fighters"
        )
    )

for fighter_result in results:
    all_scraped_fighter_data.extend(fighter_result)

Scarping UFC fighters: 100%|██████████| 26/26 [00:05<00:00,  5.06it/s]

In [31]:
fighters_df = pd.DataFrame(all_scraped_fighter_data)

fighters_df.head()

,first_name,last_name,nickname,fighter_url,height,weight,reach,stance,win,lose,draw,belt,extracted_at
0,Tom,Aaron,,http://www.ufcstats.com/fighter-details/93fe73...,--,155 lbs.,--,,5,3,0,No,2026-04-03 22:56:51
1,Danny,Abbadi,The Assassin,http://www.ufcstats.com/fighter-details/15df64...,"5' 11""",155 lbs.,--,Orthodox,4,6,0,No,2026-04-03 22:56:51
2,Nariman,Abbasov,Bayraktar,http://www.ufcstats.com/fighter-details/59a9d6...,"5' 8""",155 lbs.,"66.0""",Orthodox,28,4,0,No,2026-04-03 22:56:51
3,Darion,Abbey,,http://www.ufcstats.com/fighter-details/496146...,"6' 2""",265 lbs.,"80.0""",Orthodox,9,5,0,No,2026-04-03 22:56:51
4,David,Abbott,Tank,http://www.ufcstats.com/fighter-details/b36118...,"6' 0""",265 lbs.,--,Switch,10,15,0,No,2026-04-03 22:56:51

In [32]:
print(f"Total UFC fighters extracted: {len(fighters_df)}")

Total UFC fighters extracted: 4482

In [33]:
output_file_path=script_dir.parent/"data"/"fighters_data_scraped_test.csv"
fighters_df.to_csv(output_file_path, index=False)

### Data Testing

In [19]:
import pandas as pd
from datetime import date, datetime
from bs4 import BeautifulSoup
import requests
import time
from tqdm import tqdm
from pathlib import Path

In [55]:
url='http://www.ufcstats.com/event-details/d0d43cb9b14f231c'

headers = {'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36'}

In [56]:
response = requests.get(url, headers=headers, timeout=10)
soup = BeautifulSoup(response.text, 'html.parser')

In [57]:
rows = soup.find_all('tr', class_='b-fight-details__table-row')

# for row in rows[1:]:
fight_1=rows[1]
fight_2=rows[2]
fight_1_cols = fight_1.find_all('td', class_='b-fight-details__table-col')
fight_2_cols = fight_2.find_all('td', class_='b-fight-details__table-col')

In [58]:
fight_1_info = [p for p in fight_1_cols[0].find_all('p')]
fight_2_info = [p for p in fight_2_cols[0].find_all('p')]

In [59]:
fight_1_info

[<p class="b-fight-details__table-text">
 <a class="b-flag b-flag_style_bordered" href="http://www.ufcstats.com/fight-details/c258996570faeec9"><i class="b-flag__inner"><i class="b-flag__text">draw<i class="b-flag__corner"></i><i class="b-flag__corner-substrate"></i></i></i></a>
 </p>,
 <p class="b-fight-details__table-text">
 <a class="b-flag b-flag_style_bordered" href="http://www.ufcstats.com/fight-details/c258996570faeec9"><i class="b-flag__inner"><i class="b-flag__text">draw<i class="b-flag__corner"></i><i class="b-flag__corner-substrate"></i></i></i></a>
 </p>]

In [60]:
fight_2_info

[<p class="b-fight-details__table-text">
 <a class="b-flag b-flag_style_green" href="http://www.ufcstats.com/fight-details/b7b867eb3c3cf163"><i class="b-flag__inner"><i class="b-flag__text">win<i class="b-flag__corner"></i><i class="b-flag__corner-substrate"></i></i></i></a>
 </p>]

In [61]:
fight_1_result = [{'fight_url':r.find('a')['href'], 'result':r.find('i', class_='b-flag__text').text.strip()} for r in fight_1_info]
fight_2_result = [{'fight_url':r.find('a')['href'], 'result':r.find('i', class_='b-flag__text').text.strip()} for r in fight_2_info]

In [62]:
fight_1_result

[{'fight_url': 'http://www.ufcstats.com/fight-details/c258996570faeec9',
  'result': 'draw'},
 {'fight_url': 'http://www.ufcstats.com/fight-details/c258996570faeec9',
  'result': 'draw'}]

In [63]:
fight_1_result[0]

{'fight_url': 'http://www.ufcstats.com/fight-details/c258996570faeec9',
 'result': 'draw'}

In [64]:
fight_2_result

[{'fight_url': 'http://www.ufcstats.com/fight-details/b7b867eb3c3cf163',
  'result': 'win'}]

In [65]:
fight_2_result[0]

{'fight_url': 'http://www.ufcstats.com/fight-details/b7b867eb3c3cf163',
 'result': 'win'}